
# Generated by Qodo Gen

import pytest

class TestSimulate:

    # Simulate endpoint processes a list of CelestialBody objects correctly
    def test_simulate_with_valid_bodies(self):
        from nbodyproblem.models.bodies import CelestialBody
        from api import simulate
    
        bodies = [
            CelestialBody(name="Earth", mass=5.972e24, radius=6371, X=(0, 0, 0), V=(0, 0, 0), A=(0, 0, 0)),
            CelestialBody(name="Moon", mass=7.342e22, radius=1737, X=(384400, 0, 0), V=(0, 1.022, 0), A=(0, 0, 0))
        ]
        endtime = 1000
        timestep = 100
    
        result = simulate(bodies, endtime, timestep)
    
        assert isinstance(result, list)
        assert len(result) > 0
        assert all('name' in record for record in result)

    # Handles empty list of CelestialBody objects gracefully
    def test_simulate_with_empty_bodies(self):
        from api import simulate
    
        bodies = []
        endtime = 1000
        timestep = 100
    
        result = simulate(bodies, endtime, timestep)
    
        assert isinstance(result, list)
        assert len(result) == 0